---

scenario:
  name: version2
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: |
        "default/main.yml"
        "molecule/version2/playbook.yml"
platforms:
  - name: instance
    image: centos:7
    command: /sbin/init
    privileged: true
    published_ports:
      - 0.0.0.0:9999:80/tcp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
